#!/bin/bash
pwd
0-current_working_directory
ls -a
chmod u+x 0-current_working_directory
git config user.email hamudalwi91@gmail.com
git config user.name Hamud001
git add .
git commit -m 'working directory'
git push
